-- AlterTable
ALTER TABLE `gamehistory` MODIFY `result` BOOLEAN NOT NULL DEFAULT false,
    MODIFY `alreadyPlaying` BOOLEAN NOT NULL DEFAULT true,
    MODIFY `hp1` INTEGER NOT NULL DEFAULT 100,
    MODIFY `hp2` INTEGER NOT NULL DEFAULT 100,
    MODIFY `atk1` INTEGER NOT NULL DEFAULT 10,
    MODIFY `atk2` INTEGER NOT NULL DEFAULT 10,
    MODIFY `def1` INTEGER NOT NULL DEFAULT 10,
    MODIFY `def2` INTEGER NOT NULL DEFAULT 10,
    MODIFY `speed1` INTEGER NOT NULL DEFAULT 10,
    MODIFY `speed2` INTEGER NOT NULL DEFAULT 10;
